version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./todo_backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos
    depends_on:
      - mongo

  frontend:
    build:
      context: ./todo_frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'  # Changed from 3000:80 to 3000:3000
    environment:
      - WDS_SOCKET_PORT=0  # Required for React development server in Docker
    depends_on:
      - backend

volumes:
  mongo_data: