version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./todo_backend
      dockerfile: Dockerfile
      args:
        - MONGO_URI=mongodb://mongo:27017/todos
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos
    ports:
      - '5000:5000'  # Add this line to expose the backend port
    depends_on:
      - mongo

  frontend:
    build:
      context: ./todo_frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://backend:5000
        - WDS_SOCKET_PORT=0
    container_name: frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://backend:5000
      - WDS_SOCKET_PORT=0
    depends_on:
      - backend

volumes:
  mongo_data: